galaxy_info:
  author: Joaquin Menchaca
  description: Installs Artifactory Client Support for npm, bower, ruby, etc.
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
dependencies: []
