##################################################################
# NOTES:
#   - 200 is sucess
#   - 400 is exists already, either way it is ok
##################################################################

- name: Include Repository Key/Values
  include_vars: repos.yml

##################################################################
# Local Repositories
##################################################################
- name: Create Local Repositories
  uri:
    url:  "{{ rt_url }}/{{ rt_route.repositories }}/{{ item.key }}"
    method: PUT
    body: "{{ lookup('template','local_repo.json.j2') }}"
    status_code: 200, 400
    body_format: json
  with_dict: "{{ local_repo }}"

##################################################################
# Remote Repositories
##################################################################
- name: Create Remote Repositories
  uri:
    url: "{{ rt_url }}/{{ rt_route.repositories }}/{{ item.key }}"
    method: PUT
    body: "{{ lookup('template','remote_repo.json.j2') }}"
    status_code: 200, 400
    body_format: json
  with_dict: "{{ remote_repo }}"

##################################################################
# Virtual Repositories
##################################################################
- name: Create Virtual Repositories
  uri:
    url:  "{{ rt_url }}/{{ rt_route.repositories }}/{{ item.key }}"
    method: PUT
    body: "{{ lookup('template','virtual_repo.json.j2') }}"
    status_code: 200, 400
    body_format: json
  with_dict: "{{ virtual_repo }}"
