- name: Include Repository Key/Values
  include_vars: repos.yml

- name: Create Local Repositories
  uri:
    url: http://{{ ansible_host }}:{{ artifactory_port }}/artifactory/api/repositories/{{ item.key }}
    method: POST
    user: "{{ artifactory_admin.user }}"
    passwd: "{{ artifactory_admin.password }}"
    body: "{{ lookup('template','local_repo.json.j2') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_dict: "{{ local_repo }}"

- name: Create Remote Repositories
  uri:
    url: http://{{ ansible_host }}:{{ artifactory_port }}/artifactory/api/repositories/{{ item.key }}
    method: POST
    user: "{{ artifactory_admin.user }}"
    passwd: "{{ artifactory_admin.password }}"
    body: "{{ lookup('template','remote_repo.json.j2') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_dict: "{{ remote_repo }}"

- name: Create Virtual Repositories
  uri:
    url: http://{{ ansible_host }}:{{ artifactory_port }}/artifactory/api/repositories/{{ item.key }}
    method: POST
    user: "{{ artifactory_admin.user }}"
    passwd: "{{ artifactory_admin.password }}"
    body: "{{ lookup('template','virtual_repo.json.j2') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  with_dict: "{{ virtual_repo }}"
