---
#### INSTALL BOWER DEPENDENCIES VIA NVM NPM
- name: Test for NVM Script Library
  stat:
    path: "{{ nvm_lib }}"
  register: nvm_lib_script

- name: Install Bower Dependencies
  shell: "source {{ nvm_lib }} && npm -g install {{ item }}"
  args:
    executable: /bin/bash
  when: nvm_lib_script.stat.size != 0
  with_items:
    - "bower"
    - "bower-art-resolver"

#### CONFIGURE BOWER ARTIFACTORY SUPPORT
- name: Configure Bower Client
  template:
    src: bowerrc.j2
    dest: "/home/{{ ansible_ssh_user }}/.bowerrc"
