---
- name: Install Dependency Needed For Remote Repos
  npm:
    name: bower-art-resolver
    global: yes

- name: Configure Bower Client
  template:
    src: bowerrc.j2
    dest: "{{ ansible_ssh_user }}/.bowerrc"
