---
###### DOWNLOADE NVM INSTALLER
- name: Download NVM Installer Script
  get_url:
    url: "{{ nvm_url }}"
    dest: /tmp/install.sh
    mode: 0555

###### INSTALL NVM
- name: Install NVM using NVM Installer Script
  command: /tmp/install.sh
  args:
    creates: "{{ nvm_lib }}"

- name: Test for NVM Script Library
  stat:
    path: "{{ nvm_lib }}"
  register: nvm_lib_script

###### INSTALL NODE
- name: Install Latest Node
  shell: "source {{ nvm_lib }} && nvm install node"
  args:
    executable: /bin/bash
  when: nvm_lib_script.stat.size != 0
