---
###### DOWNLOAD RVM INSTALLER
- name: Download RVM Install Script
  get_url:
    url: "{{ rvm_url }}"
    dest: /tmp/rvm_installer
    mode: 0555

###### INSTALL RVM
- name: Install RVM
  command: /tmp/rvm_installer
  args:
    creates: "{{ rvm_lib }}"

- name: Test for RVM Script Library
  stat:
    path: "{{ rvm_lib }}"
  register: rvm_lib_script

###### INSTALL RUBY
- name: Install Latest Ruby
  shell: "source {{ rvm_lib }} && rvm install ruby"
  args:
    executable: /bin/bash
  when: rvm_lib_script.stat.size != 0
