galaxy_info:
  author: Joaquin Menchaca
  description: Installs Latest Stable Ruby via RVM
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
dependencies: []
