---
# tasks file for artifactory

# Stat File To Determine if Downloaded or not
- stat:
    path: "{{ package_path }}/{{ package_name }}"
  register: artpkg

- name: "Downlaod Artifactory Package"
  get_url:
    url: "{{ package_url }}"
    dest: "{{ package_path }}/{{ package_name }}"
  when: artpkg.stat.exists is defined and artpkg.stat.exists == False

# Stat File Again After Download
- stat:
    path: "{{ package_path }}/{{ package_name }}"
  register: artpkg

# Uncompress Package to /opt
- name: "Unarchive Artifactory Package"
  unarchive:
    remote_src: true
    src: "{{ package_path }}/{{ package_name }}"
    dest: /opt
  when: artpkg.stat.exists is defined and artpkg.stat.exists == True

# Install Package w/ Tomcat Using Artifactory's Scripts
- name: "Install Package"
  shell: ./installService.sh
  args:
    chdir: "/opt/{{ install_name }}/bin"
    creates: /etc/init.d/artifactory

# Start Service, configure to start up at bootup
- name: "Start Service"
  service:
    name: artifactory
    state: started
    enabled: yes
