---
# tasks file for artifactory
- stat:
    path: "{{ package_path }}/{{ package_name }}"
  register: artpkg

- name: "Downlaod Artifactory Package"
  get_url:
    url: "{{ package_url }}"
    dest: "{{ package_path }}/{{ package_name }}"
  when: artpkg.stat.exists is defined and artpkg.stat.exists == False

- name: "Unarchive Artifactory Package"
  unarchive:
    remote_src: true
    src: "{{ package_path }}/{{ package_name }}"
    dest: /opt
  when: artpkg.stat.exists is defined and artpkg.stat.exists == True


- name: "Install Package"
  shell: ./installService.sh
  args:
    chdir: "/opt/{{ install_name }}/bin"
    creates: /etc/init.d/artifactory

- name: "Start Service"
  service:
    name: artifactory
    state: started
    enabled: yes
