---
# tasks file for artifactory
# - stat:
#     path: "{{ package_path }}/{{ package_name }}"
#   register: artpkg
#
# - name: "Downlaod Artifactory Package"
#   get_url:
#     url: "{{ package_url }}"
#     dest: "{{ package_path }}/{{ package_name }}"
#   when: artpkg.stat.exists is defined and artpkg.stat.exists == False

# - name: "Copy Artifcatory Package"
#   copy:
#     src: "{{ package_path }}/{{ package_name }}"
#     dest: "/opt/{{ package_name }}"
#   when: artpkg.stat.exists is defined and artpkg.stat.exists == True

# - unarchive:
#     src: "{{ package_path }}/{{ package_name }}"
#     dest: /opt

- unarchive:
    src: /vagrant/packages/jfrog-artifactory-oss-4.15.0.zip
    dest: /opt

# - shell: cp "{{ package_path }}/{{ package_name }}" /opt
#
# - unarchive:
#     src: "{{ artpkg.stat.path }}"
#     dest: /opt

# - name: "Copy Artifcatory Package"
#   copy:
#     src: "{{ package_path }}/{{ package_name }}"
#     dest: "/opt/{{ package_name }}"
#   when: artpkg.stat.exists is defined and artpkg.stat.exists == True
